apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
  labels:
{{- include "cupsd.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: {{ .Values.name }}
  selector:
    app: {{ template "cupsd.name" . }}
    release: {{ .Release.Name }}
